=== StratoCasterFen/Strato/sprdao/dxdb/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="hiberpolice_test">
	<xsd:import namespace="hiberpolice_test" schemaLocation="hiberpolice_test.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="criminalevents" type="dflt:criminalevents__type" />
				<xsd:element name="eventlinks" type="dflt:eventlinks__type" />
				<xsd:element name="user_role" type="dflt:user_role__type" />
				<xsd:element name="criminals" type="dflt:criminals__type" />
				<xsd:element name="roles" type="dflt:roles__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="eventtype" type="dflt:eventtype__type" />
				<xsd:element name="users" type="dflt:users__type" />
				<xsd:any namespace="hiberpolice_test" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== StratoCasterFen/Strato/dao/src/test/java/by/academy/mydao/policetest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dbxsd/dataset.xsd">
	
   <users Userid="1" UserName="Jim" password="19990101"/>
   <users Userid="2" UserName="Tom" password="78451891"/>
   <users Userid="3" UserName="Marta" password="198425oo1"/>
   
   <roles RoleId="1" RoleName="Admin"/>
   <roles RoleId="2" RoleName="Looser"/>
   
   <user_role IdUR="1" UserId="1" RoleId="1"/>
   <user_role IdUR="2" UserId="2" RoleId="2"/>
   <user_role IdUR="3" UserId="2" RoleId="2"/>
   
   <criminal CriminalId="1" Name="Kevin" SurName="Mitnik" BirthDay="1970-01-04"/>
   <criminal CriminalId="2" Name="Bobo" SurName="Little" BirthDay="1974-11-14"/>
   
   <criminalevents EventId="1" EventName="Vzlom" EventDescription="Broke telefon box" EventDate="2015-08-03" CriminalId="1" UserId="2"/>
   <criminalevents EventId="2" EventName="Ograblenie" EventDescription="Ograblenie JP Morgan bank" EventDate="2014-02-07"/>
   
</dataset>

=== StratoCasterFen/Strato/hiberdao/src/test/resources/by/academy/HiberDbTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dbxsd/dataset.xsd">
	
   <users username="Jim" id="1" password="19990101"/>
   <users username="Tom" id="2" password="78451891"/>
   <users username="Marta" id="3" password="198425oo1"/>
  
   <roles Id="1" RoleName="Admin"/>
   <roles Id="2" RoleName="Looser"/>
   
   <user_role Id="1" UserId="1" RoleId="1"/>
   <user_role Id="2" UserId="2" RoleId="2"/>
   <user_role Id="3" UserId="2" RoleId="2"/>
   
   <criminals Id="1" Name="Kevin" SurName="Mitnik" BirthDay="1970-01-04"/>
   <criminals Id="2" Name="Bobo" SurName="Little" BirthDay="1974-11-14"/>
   
    
</dataset>

=== StratoCasterFen/Strato/hiberdao/target/test-classes/by/academy/HiberDbTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dbxsd/dataset.xsd">
	
   <users username="Jim" id="1" password="19990101"/>
   <users username="Tom" id="2" password="78451891"/>
   <users username="Marta" id="3" password="198425oo1"/>
  
   <roles Id="1" RoleName="Admin"/>
   <roles Id="2" RoleName="Looser"/>
   
   <user_role Id="1" UserId="1" RoleId="1"/>
   <user_role Id="2" UserId="2" RoleId="2"/>
   <user_role Id="3" UserId="3" RoleId="2"/>
   <user_role Id="4" UserId="2" RoleId="1"/>
   
   <criminals Id="1" Name="Kevin" SurName="Mitnik" BirthDay="1970-01-04"/>
   <criminals Id="2" Name="Bobo" SurName="Little" BirthDay="1974-11-14"/>
   
   <criminalevents id ="1" name="first event" description="blabla-bla" eventdate="2015-08-30"/>
   <criminalevents id ="2" name="second event" description="uydublabla-bla" eventdate="2015-08-31"/>
   
   <eventlinks id="1" eventid="1" eventtypeid="1" userid="2" criminalid="1"/>
   <eventlinks id="2" eventid="2" eventtypeid="2" userid="1" criminalid="2"/>
   
   <eventtype id="1" typename="grabeg"/>
   <eventtype id="2" typename="draka"/> 
   
</dataset>
